version: "3.5"

services:
    kwmc-frontend:
        image: nginx
        ports:
        - 3000:80
        container_name: "kwmc-frontend"
        restart: unless-stopped
        volumes:
        - ../dist:/usr/share/nginx/html:ro
        - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    dist:
